### ISSUE TITLE
Issue with Version 2.0

### ISSUE THREAD

**Issue by bummzack** [bigfork/htmleditorsrcset#1]
With SilverStripe 4.0, I get the following error after installation:

    Call to undefined method SilverStripe\Assets\Image::find_shortcode_record()

I think the proper class to use would be `ImageShortcodeProvider` instead of `Image`, but there's another issue where `find_error_record` has been marked as protected.

Also, could this module be turned into a vendormodule?

**Comment by lozcalver** [comment]
Yep, that’ll teach me for tagging a stable release against 4.0.0-alpha1 😅
